<a href="https://colab.research.google.com/github/Hasib0077/nlp1/blob/main/pipeline_work.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
from transformers import AutoTokenizer
checkpoint="distilbert-base-uncased-finetuned-sst-2-english"
tokenizer=AutoTokenizer.from_pretrained(checkpoint)

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


In [23]:
raw_inputs=[
     "I've been waiting for a HuggingFace course my whole life.",
    "I hate this so much!"
]
inputs=tokenizer(raw_inputs, padding=True, truncation=True,return_tensors="tf")


In [27]:
from transformers import TFAutoModelForSequenceClassification
checkpoint="distilbert-base-uncased-finetuned-sst-2-english"
model=TFAutoModelForSequenceClassification.from_pretrained(checkpoint)



All PyTorch model weights were used when initializing TFDistilBertForSequenceClassification.

All the weights of TFDistilBertForSequenceClassification were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertForSequenceClassification for predictions without further training.


In [30]:
outputs=model(inputs)
outputs.logits.shape #two sentences two lebeled

TensorShape([2, 2])

In [32]:
outputs.logits #Our model predicted [-1.5607, 1.6123] for the first sentence and [ 4.1692, -3.3464] for the second one

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.5606961,  1.6122813],
       [ 4.1692314, -3.3464477]], dtype=float32)>

In [35]:
#Now we can see that the model predicted [0.0402, 0.9598] for the first sentence and [0.9995, 0.0005] for the second one
import tensorflow as tf
predictions=tf.math.softmax(outputs.logits,axis=-1)
predictions

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[4.0195391e-02, 9.5980465e-01],
       [9.9945587e-01, 5.4418371e-04]], dtype=float32)>

In [34]:
#To get the labels corresponding to each position, we can inspect the id2label attribute of the model config
model.config.id2label

{0: 'NEGATIVE', 1: 'POSITIVE'}